// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam_app/test/domain/use_case/auth_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam_app/domain/common/result.dart' as _i4;
import 'package:online_exam_app/domain/entity/forget_response_password_entity.dart'
    as _i7;
import 'package:online_exam_app/domain/entity/login_response_entity.dart'
    as _i5;
import 'package:online_exam_app/domain/entity/reset_password_response_entity.dart'
    as _i9;
import 'package:online_exam_app/domain/entity/sign_up_request.dart' as _i11;
import 'package:online_exam_app/domain/entity/sign_up_response.dart' as _i10;
import 'package:online_exam_app/domain/entity/verify_email_response_entity.dart'
    as _i8;
import 'package:online_exam_app/domain/repository/auth_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.LoginResponseEntity>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.LoginResponseEntity>>.value(
            _i6.dummyValue<_i4.Result<_i5.LoginResponseEntity>>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.LoginResponseEntity>>);

  @override
  _i3.Future<_i4.Result<_i7.ForgetResponsePasswordEntity>> forgetPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue:
            _i3.Future<_i4.Result<_i7.ForgetResponsePasswordEntity>>.value(
                _i6.dummyValue<_i4.Result<_i7.ForgetResponsePasswordEntity>>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i7.ForgetResponsePasswordEntity>>);

  @override
  _i3.Future<_i4.Result<_i8.VerifyEmailResponseEntity>> verifyEmail(
          String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [code],
        ),
        returnValue:
            _i3.Future<_i4.Result<_i8.VerifyEmailResponseEntity>>.value(
                _i6.dummyValue<_i4.Result<_i8.VerifyEmailResponseEntity>>(
          this,
          Invocation.method(
            #verifyEmail,
            [code],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i8.VerifyEmailResponseEntity>>);

  @override
  _i3.Future<_i4.Result<_i9.ResetPasswordResponseEntity>> resetPassword(
    String? email,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            email,
            newPassword,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<_i9.ResetPasswordResponseEntity>>.value(
                _i6.dummyValue<_i4.Result<_i9.ResetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #resetPassword,
            [
              email,
              newPassword,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i9.ResetPasswordResponseEntity>>);

  @override
  _i3.Future<_i4.Result<_i10.UserModel>> signUp(_i11.SignUpRequest? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [data],
        ),
        returnValue: _i3.Future<_i4.Result<_i10.UserModel>>.value(
            _i6.dummyValue<_i4.Result<_i10.UserModel>>(
          this,
          Invocation.method(
            #signUp,
            [data],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i10.UserModel>>);
}
